services:
  - type: web
    name: agrikaro-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: Farm Accounts API
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: POSTGRES_USER
        value: postgres.ifezrdgcotfqqwdjogvy
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_HOST
        value: aws-0-ap-southeast-2.pooler.supabase.com
      - key: POSTGRES_PORT
        value: "5432"
      - key: POSTGRES_DBNAME
        value: postgres
      - key: POSTGRES_SSLMODE
        value: require
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: CORS_ORIGINS
        value: https://agrikaro.netlify.app,http://localhost:5173
